# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(blank=True, db_column='course_id', max_length=45, null=True)),
                ('course_name', models.CharField(blank=True, db_column='course_name', max_length=45, null=True)),
                ('student_type', models.CharField(blank=True, db_column='student_type', max_length=45, null=True)),
                ('year', models.CharField(blank=True, db_column='year', max_length=45, null=True)),
                ('class_name', models.CharField(blank=True, db_column='class_name', max_length=45, null=True)),
                ('semester', models.CharField(blank=True, db_column='semester', max_length=45, null=True)),
                ('course_hour', models.FloatField(blank=True, db_column='course_hour', null=True)),
                ('course_degree', models.FloatField(blank=True, db_column='course_degree', null=True)),
                ('course_type', models.CharField(blank=True, db_column='course_type', max_length=45, null=True)),
                ('allow_teachers', models.IntegerField(db_column='allow_teachers')),
                ('times_every_week', models.IntegerField(db_column='times_every_week')),
                ('suit_teacher', models.CharField(blank=True, db_column='suit_teacher', max_length=200, null=True)),
                ('teacher_ordered', models.CharField(blank=True, db_column='teacher_ordered', max_length=200, null=True)),
                ('teacher_auto_pick', models.CharField(blank=True, db_column='teacher_auto_pick', max_length=200, null=True)),
                ('teacher_final_pick', models.CharField(blank=True, db_column='teacher_final_pick', max_length=200, null=True)),
                ('update_time', models.DateTimeField(blank=True, db_column='update_time', null=True)),
            ],
            options={
                'db_table': 'course_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurrentStepInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrange_class_status', models.CharField(blank=True, db_column='arrange_class_status', max_length=45, null=True)),
                ('s1_year_info', models.CharField(blank=True, db_column='s1_year_info', max_length=45, null=True)),
                ('s2_undergraduate', models.CharField(blank=True, db_column='s2_undergraduate', max_length=45, null=True)),
                ('s2_postgraduate_1', models.CharField(blank=True, db_column='s2_postgraduate_1', max_length=45, null=True)),
                ('s2_postgraduate_2', models.CharField(blank=True, db_column='s2_postgraduate_2', max_length=45, null=True)),
                ('s2_doctor', models.CharField(blank=True, db_column='s2_doctor', max_length=45, null=True)),
                ('s2_start_request', models.CharField(blank=True, db_column='s2_start_request', max_length=45, null=True)),
                ('s2_deadline', models.DateTimeField(blank=True, db_column='s2_deadline', null=True)),
                ('s2_teacher_confirm_u', models.CharField(blank=True, db_column='s2_teacher_confirm_u', max_length=45, null=True)),
                ('s2_teacher_confirm_p1', models.CharField(blank=True, db_column='s2_teacher_confirm_p1', max_length=45, null=True)),
                ('s2_teacher_confirm_p2', models.CharField(blank=True, db_column='s2_teacher_confirm_p2', max_length=45, null=True)),
                ('s2_teacher_confirm_d', models.CharField(blank=True, db_column='s2_teacher_confirm_d', max_length=45, null=True)),
                ('s3_status_flag', models.CharField(blank=True, db_column='s3_status_flag', max_length=45, null=True)),
                ('s4_status_flag', models.CharField(blank=True, db_column='s4_status_flag', max_length=45, null=True)),
                ('s4_teacher_confirm_u', models.CharField(blank=True, db_column='s4_teacher_confirm_u', max_length=45, null=True)),
                ('s4_teacher_confirm_p1', models.CharField(blank=True, db_column='s4_teacher_confirm_p1', max_length=45, null=True)),
                ('s4_teacher_confirm_p2', models.CharField(blank=True, db_column='s4_teacher_confirm_p2', max_length=45, null=True)),
                ('s4_teacher_confirm_d', models.CharField(blank=True, db_column='s4_teacher_confirm_d', max_length=45, null=True)),
                ('s5_status_flag', models.CharField(blank=True, db_column='s5_status_flag', max_length=45, null=True)),
            ],
            options={
                'db_table': 'current_step_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField(db_column='teacher_id')),
                ('teacher_name', models.CharField(blank=True, db_column='teacher_name', max_length=45, null=True)),
                ('first_semester_expect', models.FloatField(blank=True, db_column='first_semester_expect', null=True)),
                ('second_semester_expect', models.FloatField(blank=True, db_column='second_semester_expect', null=True)),
                ('first_semester_hours', models.FloatField(blank=True, db_column='first_semester_hours', null=True)),
                ('second_semester_hours', models.FloatField(blank=True, db_column='second_semester_hours', null=True)),
                ('first_semester_degree', models.FloatField(blank=True, db_column='first_semester_degree', null=True)),
                ('second_semester_degree', models.FloatField(blank=True, db_column='second_semester_degree', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_column='update_time', null=True)),
            ],
            options={
                'db_table': 'teacher_info',
                'managed': False,
            },
        ),
    ]
